from __future__ import annotations

CAP_EXECUCAO_CHAMADO_VER = "execucao.chamado_ver"
CAP_EXECUCAO_CHAMADO_EDITAR = "execucao.chamado_editar"
CAP_EXECUCAO_CHAMADO_FINALIZAR = "execucao.chamado_finalizar"
CAP_EXECUCAO_SESSAO_TOMAR = "execucao.sessao_tomar"

EXECUCAO_CAPABILITIES: list[str] = [
    CAP_EXECUCAO_CHAMADO_VER,
    CAP_EXECUCAO_CHAMADO_EDITAR,
    CAP_EXECUCAO_CHAMADO_FINALIZAR,
    CAP_EXECUCAO_SESSAO_TOMAR,
]

# Papéis base (contrato do produto)
ROLE_TECNICO: list[str] = [
    CAP_EXECUCAO_CHAMADO_VER,
    CAP_EXECUCAO_CHAMADO_EDITAR,
]

ROLE_COORDENADOR: list[str] = [
    CAP_EXECUCAO_CHAMADO_VER,
    CAP_EXECUCAO_CHAMADO_EDITAR,
    CAP_EXECUCAO_CHAMADO_FINALIZAR,
]

ROLE_ADMIN_OPERACIONAL: list[str] = [
    CAP_EXECUCAO_CHAMADO_VER,
    CAP_EXECUCAO_CHAMADO_EDITAR,
    CAP_EXECUCAO_CHAMADO_FINALIZAR,
    CAP_EXECUCAO_SESSAO_TOMAR,
]
