# Generated by Django 5.2.9 on 2026-01-23 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Capability",
                "verbose_name_plural": "Capabilities",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.capability"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Capability",
                "verbose_name_plural": "User Capabilities",
                "indexes": [
                    models.Index(
                        fields=["user", "capability"], name="iam_usercap_user_id_933eb0_idx"
                    ),
                    models.Index(fields=["capability"], name="iam_usercap_capabil_9dedc7_idx"),
                ],
                "unique_together": {("user", "capability")},
            },
        ),
    ]
