# Generated by Django 5.2.14 on 2026-05-31 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='iam.capability')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='auth.group')),
            ],
            options={
                'verbose_name': 'Capability do Grupo',
                'verbose_name_plural': 'Capabilities dos Grupos',
                'unique_together': {('group', 'capability')},
            },
        ),
    ]
