# Generated by Django 5.2.9 on 2026-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilRede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Chave única e estável"
                        "(ex: LEGACY_FLAT_2023, RD_SEGMENTADO_2024).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LEGACY_FLAT", "Legacy Flat"), ("SEGMENTADO", "Segmentado")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Rede",
                "verbose_name_plural": "Perfis de Rede",
                "ordering": ("codigo",),
            },
        ),
    ]
