# Generated by Django 5.2.11 on 2026-02-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilRede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=64, unique=True)),
                ("descricao", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LEGACY_FLAT", "Legacy Flat"),
                            ("SEGMENTADO", "Segmentado"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Rede",
                "verbose_name_plural": "Perfis de Rede",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="RegraRedeEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Tipo do equipamento (ex: PDV, TC, CONSULTA_PRECO).",
                        max_length=64,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "ip_policy",
                    models.CharField(
                        choices=[
                            ("OFFSET_FIXO", "Offset fixo"),
                            ("SEQUENCIAL", "Sequencial"),
                            ("FAIXA", "Faixa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("offset_fixo", models.IntegerField(blank=True, null=True)),
                ("offset_inicio", models.IntegerField(blank=True, null=True)),
                ("offset_fim", models.IntegerField(blank=True, null=True)),
                ("offset_base", models.IntegerField(blank=True, null=True)),
                ("reservados", models.JSONField(blank=True, null=True)),
                (
                    "perfil_rede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regras_equipamento",
                        to="redes.perfilrede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Rede por Equipamento",
                "verbose_name_plural": "Regras de Rede por Equipamento",
                "ordering": ("perfil_rede__codigo", "codigo"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("perfil_rede", "codigo"),
                        name="uniq_regra_rede_equipamento_por_perfil_codigo",
                    )
                ],
            },
        ),
    ]
