# Generated by Django 5.2.9 on 2026-02-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("redes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilrede",
            name="codigo",
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name="RegraRedeEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Tipo do equipamento (ex: PDV, TC, CONSULTA_PRECO).",
                        max_length=64,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "ip_policy",
                    models.CharField(
                        choices=[
                            ("OFFSET_FIXO", "Offset fixo"),
                            ("SEQUENCIAL", "Sequencial"),
                            ("FAIXA", "Faixa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("offset_fixo", models.IntegerField(blank=True, null=True)),
                ("offset_inicio", models.IntegerField(blank=True, null=True)),
                ("offset_fim", models.IntegerField(blank=True, null=True)),
                ("offset_base", models.IntegerField(blank=True, null=True)),
                ("reservados", models.JSONField(blank=True, null=True)),
                (
                    "perfil_rede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regras_equipamento",
                        to="redes.perfilrede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Rede por Equipamento",
                "verbose_name_plural": "Regras de Rede por Equipamento",
                "ordering": ("perfil_rede__codigo", "codigo"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("perfil_rede", "codigo"),
                        name="uniq_regra_rede_equipamento_por_perfil_codigo",
                    )
                ],
            },
        ),
    ]
