# Generated by Django 5.2.11 on 2026-02-14 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cadastro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENVIO", "Envio (Matriz → Loja)"),
                            ("RETORNO", "Retorno (Loja → Matriz)"),
                        ],
                        default="ENVIO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ABERTURA", "Em abertura"),
                            ("ABERTO", "Aberto"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("AGUARDANDO_NF", "Aguardando NF"),
                            ("AGUARDANDO_COLETA", "Aguardando coleta"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        db_index=True,
                        default="EM_ABERTURA",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("MAIS_ANTIGO", "Padrão"),
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        db_index=True,
                        default="MAIS_ANTIGO",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "protocolo",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "ticket_externo_sistema",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "ticket_externo_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("coleta_confirmada_em", models.DateTimeField(blank=True, null=True)),
                ("coleta_confirmada", models.BooleanField(default=False)),
                (
                    "contabilidade_numero",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                (
                    "nf_saida_numero",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                (
                    "chamado_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chamado de origem (obrigatório quando tipo=RETORNO).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retornos",
                        to="chamados.chamado",
                    ),
                ),
                (
                    "coleta_confirmada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados_coleta_confirmada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.kit"
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.loja"
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.projeto",
                    ),
                ),
                (
                    "subprojeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.subprojeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenciaChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NF_SAIDA", "NF Saída"),
                            ("NF_RETORNO", "NF Retorno"),
                            ("CARTA_CONTEUDO", "Carta de Conteúdo"),
                            ("EXCECAO", "Exceção"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="execucao/evidencias/")),
                ("descricao", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="chamados.chamado",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InstalacaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=80)),
                ("quantidade", models.PositiveIntegerField()),
                ("tem_ativo", models.BooleanField()),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "requer_configuracao",
                    models.BooleanField(
                        default=False,
                        help_text="(Compat) Informação vinda do kit. A obrigatoriedade é decidida no chamado.",
                    ),
                ),
                (
                    "deve_configurar",
                    models.BooleanField(
                        default=False,
                        help_text="Decisão do chamado: este item deve ser configurado?",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status_configuracao",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("CONFIGURADO", "Configurado"),
                        ],
                        default="AGUARDANDO",
                        help_text="Estado atual do processo de configuração do item.",
                        max_length=20,
                    ),
                ),
                ("configurado_em", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.CharField(blank=True, default="", max_length=80)),
                (
                    "numero_serie",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status_retorno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RETORNADO", "Retornado"),
                            ("NAO_RETORNADO", "Não retornado"),
                        ],
                        default=None,
                        help_text="Obrigatório para itens em Chamado do tipo RETORNO.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "motivo_nao_retorno",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Obrigatório quando status_retorno=NAO_RETORNADO.",
                        max_length=255,
                    ),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="chamados.chamado",
                    ),
                ),
                (
                    "configurado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucao_itens_configurados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.equipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Instalação",
                "verbose_name_plural": "Itens de Instalação",
            },
        ),
        migrations.CreateModel(
            name="ItemConfiguracaoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "de_status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("CONFIGURADO", "Configurado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "para_status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("CONFIGURADO", "Configurado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_configuracao_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_configuracao",
                        to="chamados.instalacaoitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="chamado",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ticket_externo_sistema__isnull", False),
                    models.Q(("ticket_externo_sistema", ""), _negated=True),
                    ("ticket_externo_id__isnull", False),
                    models.Q(("ticket_externo_id", ""), _negated=True),
                ),
                fields=("ticket_externo_sistema", "ticket_externo_id"),
                name="uq_chamado_ticket_externo_sistema_id",
            ),
        ),
    ]
