# Generated by Django 5.2.14 on 2026-05-30 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('EM_ABERTURA', 'Em abertura'), ('ABERTO', 'Aberto'), ('EM_CONFIGURACAO', 'Em configuração'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_NF', 'Aguardando NF'), ('AGUARDANDO_COLETA', 'Aguardando coleta'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EM_ABERTURA', max_length=20),
        ),
    ]
