# Generated by Django 5.2.11 on 2026-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chamados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenciachamado",
            name="nome_arquivo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
