# Generated by Django 5.2.14 on 2026-06-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('chamados', '0002_add_status_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='is_avulso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.kit'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.projeto'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='subprojeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.subprojeto'),
        ),
    ]
