# Generated by Django 5.2.14 on 2026-05-31 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('TECNICO', 'Técnico de Campo'), ('COORDENADOR', 'Coordenador'), ('LOGISTICA', 'Logística'), ('AUDITOR', 'Auditor'), ('ADMINISTRADOR', 'Administrador')], default='TECNICO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('BLOQUEADO', 'Bloqueado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20)),
                ('equipe', models.CharField(blank=True, default='', max_length=80)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
