# Generated by Django 5.2.11 on 2026-02-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CodeSequence",
            fields=[
                (
                    "prefix",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sequência de Código",
                "verbose_name_plural": "Sequências de Código",
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "cor_slug",
                    models.CharField(
                        choices=[
                            ("SLATE", "Cinza"),
                            ("BLUE", "Azul"),
                            ("EMERALD", "Verde"),
                            ("VIOLET", "Roxo"),
                            ("AMBER", "Amarelo"),
                            ("ROSE", "Rosa"),
                            ("CYAN", "Ciano"),
                            ("LIME", "Lima"),
                        ],
                        default="SLATE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
                ("tem_ativo", models.BooleanField(default=True)),
                ("configuravel", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipamentos",
                        to="cadastro.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
                ("hist", models.CharField(blank=True, default="", max_length=50)),
                ("endereco", models.CharField(blank=True, default="", max_length=255)),
                ("bairro", models.CharField(blank=True, default="", max_length=120)),
                ("cidade", models.CharField(blank=True, default="", max_length=120)),
                ("uf", models.CharField(blank=True, default="", max_length=2)),
                ("logomarca", models.CharField(blank=True, default="", max_length=80)),
                ("telefone", models.CharField(blank=True, default="", max_length=60)),
                ("ip_banco_12", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
                "indexes": [
                    models.Index(fields=["hist"], name="loja_hist_idx"),
                    models.Index(fields=["uf"], name="loja_uf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subprojeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprojetos",
                        to="cadastro.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subprojeto",
                "verbose_name_plural": "Subprojetos",
            },
        ),
        migrations.CreateModel(
            name="TipoEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("nome", models.CharField(max_length=80)),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos",
                        to="cadastro.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Equipamento",
                "verbose_name_plural": "Tipos de Equipamento",
                "unique_together": {("categoria", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ItemKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "requer_configuracao",
                    models.BooleanField(
                        default=False,
                        help_text="Define se este item exige configuração técnica neste kit.",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.equipamento",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cadastro.kit",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.tipoequipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Kit",
                "verbose_name_plural": "Itens do Kit",
                "unique_together": {("kit", "equipamento", "tipo")},
            },
        ),
    ]
