# Generated by Django 5.2.9 on 2026-01-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
            },
        ),
        migrations.CreateModel(
            name="ItemKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cadastro.kit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Kit",
                "verbose_name_plural": "Itens do Kit",
                "unique_together": {("kit", "nome")},
            },
        ),
    ]
