# Generated by Django 5.2.9 on 2026-01-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=120)),
                ("configuravel", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipamentos",
                        to="cadastro.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.CreateModel(
            name="ItemKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tipo", models.CharField(max_length=80)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.equipamento"
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cadastro.kit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Kit",
                "verbose_name_plural": "Itens do Kit",
                "unique_together": {("kit", "equipamento", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="Subprojeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=120)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprojetos",
                        to="cadastro.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subprojeto",
                "verbose_name_plural": "Subprojetos",
                "unique_together": {("projeto", "codigo")},
            },
        ),
    ]
