# Generated by Django 5.2.9 on 2026-01-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemkit",
            name="requer_configuracao",
            field=models.BooleanField(
                default=False, help_text="Define se este item exige configuração técnica neste kit."
            ),
        ),
    ]
