# Generated by Django 5.2.9 on 2026-02-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0002_itemkit_requer_configuracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="loja",
            name="bairro",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="loja",
            name="cidade",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="loja",
            name="endereco",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="loja",
            name="hist",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="loja",
            name="ip_banco_12",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loja",
            name="logomarca",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="loja",
            name="telefone",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="loja",
            name="uf",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
