# Generated by Django 5.2.9 on 2026-02-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0003_loja_bairro_loja_cidade_loja_endereco_loja_hist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=80)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos",
                        to="cadastro.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Equipamento",
                "verbose_name_plural": "Tipos de Equipamento",
                "unique_together": {("categoria", "codigo")},
            },
        ),
    ]
