# Generated by Django 5.2.9 on 2026-02-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0004_tipoequipamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemkit",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cadastro.tipoequipamento"
            ),
        ),
    ]
