# Generated by Django 5.2.9 on 2026-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0005_alter_itemkit_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoequipamento",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
