# Generated by Django 5.2.9 on 2026-02-04 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0006_alter_tipoequipamento_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tipoequipamento",
            old_name="ativo",
            new_name="disponivel",
        ),
    ]
