# Generated by Django 5.2.9 on 2026-02-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0007_rename_ativo_tipoequipamento_disponivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="cor_slug",
            field=models.CharField(
                choices=[
                    ("SLATE", "Cinza"),
                    ("BLUE", "Azul"),
                    ("EMERALD", "Verde"),
                    ("VIOLET", "Roxo"),
                    ("AMBER", "Amarelo"),
                    ("ROSE", "Rosa"),
                    ("CYAN", "Ciano"),
                    ("LIME", "Lima"),
                ],
                default="SLATE",
                max_length=20,
            ),
        ),
    ]
