# Generated by Django 5.2.9 on 2026-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0008_projeto_cor_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loja",
            index=models.Index(fields=["hist"], name="loja_hist_idx"),
        ),
        migrations.AddIndex(
            model_name="loja",
            index=models.Index(fields=["uf"], name="loja_uf_idx"),
        ),
    ]
