# Generated by Django 5.2.9 on 2026-02-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0010_codesequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={},
        ),
        migrations.AlterModelOptions(
            name="codesequence",
            options={
                "verbose_name": "Sequência de Código",
                "verbose_name_plural": "Sequências de Código",
            },
        ),
        migrations.AddField(
            model_name="categoria",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
