# Generated by Django 5.2.9 on 2026-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cadastro",
            "0011_alter_categoria_options_alter_codesequence_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
