# Generated by Django 5.2.9 on 2026-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0012_alter_equipamento_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
