# Generated by Django 5.2.9 on 2026-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0013_alter_projeto_codigo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subprojeto",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subprojeto",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
