# Generated by Django 5.2.11 on 2026-02-14 17:05

import django.db.models.deletion
import django.utils.timezone
import execucao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chamados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("ADMIN_TAKE", "Admin tomou a sessão")], max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to="chamados.chamado",
                    ),
                ),
                (
                    "new_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(default=execucao.models._default_expires_at),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("TIMEOUT", "Timeout"),
                            ("OUTRO", "Outro"),
                            ("ADMIN_TAKE", "Admin tomou a sessão"),
                            ("SAVE", "Salvar execução"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_sessions",
                        to="chamados.chamado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["chamado", "ended_at"],
                        name="execucao_ex_chamado_d01c5c_idx",
                    ),
                    models.Index(
                        fields=["usuario", "ended_at"],
                        name="execucao_ex_usuario_988b76_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="execucao_ex_expires_292641_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("chamado",),
                        name="uniq_open_execution_session_per_chamado",
                    )
                ],
            },
        ),
    ]
