# Generated by Django 5.2.9 on 2026-01-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.kit"
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.loja"
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.projeto"
                    ),
                ),
                (
                    "subprojeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.subprojeto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstalacaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tipo", models.CharField(max_length=80)),
                ("quantidade", models.PositiveIntegerField()),
                ("tem_ativo", models.BooleanField()),
                ("confirmado", models.BooleanField(default=False)),
                ("ativo", models.CharField(blank=True, default="", max_length=80)),
                ("numero_serie", models.CharField(blank=True, default="", max_length=120)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="execucao.chamado",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastro.equipamento"
                    ),
                ),
            ],
        ),
    ]
