# Generated by Django 5.2.9 on 2026-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="finalizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
