# Generated by Django 5.2.9 on 2026-01-21 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0002_chamado_finalizado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="contabilidade_numero",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="chamado",
            name="nf_saida_numero",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="chamado",
            name="protocolo",
            field=models.CharField(
                default=django.utils.timezone.now, editable=False, max_length=32, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chamado",
            name="servicenow_numero",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
