# Generated by Django 5.2.9 on 2026-01-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0003_chamado_contabilidade_numero_chamado_nf_saida_numero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NF_SAIDA", "NF Saída"),
                            ("NF_RETORNO", "NF Retorno"),
                            ("CARTA_CONTEUDO", "Carta de Conteúdo"),
                            ("EXCECAO", "Exceção"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="execucao/evidencias/")),
                ("descricao", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="execucao.chamado",
                    ),
                ),
            ],
        ),
    ]
