# Generated by Django 5.2.9 on 2026-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0004_evidenciachamado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instalacaoitem",
            options={
                "verbose_name": "Item de Instalação",
                "verbose_name_plural": "Itens de Instalação",
            },
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="requer_configuracao",
            field=models.BooleanField(
                default=False,
                help_text="Define se o item necessita de configuração técnica após instalação.",
            ),
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="status_configuracao",
            field=models.CharField(
                choices=[
                    ("AGUARDANDO", "Aguardando"),
                    ("EM_CONFIGURACAO", "Em configuração"),
                    ("CONFIGURADO", "Configurado"),
                ],
                default="AGUARDANDO",
                help_text="Estado atual do processo de configuração do item.",
                max_length=20,
            ),
        ),
    ]
