# Generated by Django 5.2.9 on 2026-01-23 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0005_alter_instalacaoitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemConfiguracaoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "de_status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("CONFIGURADO", "Configurado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "para_status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("EM_CONFIGURACAO", "Em configuração"),
                            ("CONFIGURADO", "Configurado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_configuracao_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_configuracao",
                        to="execucao.instalacaoitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
    ]
