# Generated by Django 5.2.9 on 2026-01-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0006_itemconfiguracaolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="chamado_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Chamado de origem (obrigatório quando tipo=RETORNO).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retornos",
                to="execucao.chamado",
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENVIO", "Envio (Matriz → Loja)"),
                    ("RETORNO", "Retorno (Loja → Matriz)"),
                ],
                default="ENVIO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemconfiguracaolog",
            name="motivo_nao_retorno",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Obrigatório quando status_retorno=NAO_RETORNADO.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="itemconfiguracaolog",
            name="status_retorno",
            field=models.CharField(
                blank=True,
                choices=[("RETORNADO", "Retornado"), ("NAO_RETORNADO", "Não retornado")],
                default=None,
                help_text="Obrigatório para itens em Chamado do tipo RETORNO.",
                max_length=20,
                null=True,
            ),
        ),
    ]
