# Generated by Django 5.2.9 on 2026-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0007_chamado_chamado_origem_chamado_tipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemconfiguracaolog",
            name="motivo_nao_retorno",
        ),
        migrations.RemoveField(
            model_name="itemconfiguracaolog",
            name="status_retorno",
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="motivo_nao_retorno",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Obrigatório quando status_retorno=NAO_RETORNADO.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="status_retorno",
            field=models.CharField(
                blank=True,
                choices=[("RETORNADO", "Retornado"), ("NAO_RETORNADO", "Não retornado")],
                default=None,
                help_text="Obrigatório para itens em Chamado do tipo RETORNO.",
                max_length=20,
                null=True,
            ),
        ),
    ]
