# Generated by Django 5.2.9 on 2026-01-25 01:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0008_remove_itemconfiguracaolog_motivo_nao_retorno_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidenciachamado",
            options={"ordering": ["-criado_em", "-id"]},
        ),
    ]
