# Generated by Django 5.2.9 on 2026-02-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0009_alter_evidenciachamado_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacaoitem",
            name="deve_configurar",
            field=models.BooleanField(
                default=False, help_text="Decisão do chamado: este item deve ser configurado?"
            ),
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instalacaoitem",
            name="requer_configuracao",
            field=models.BooleanField(
                default=False,
                help_text="(Compat) Informação vinda do kit."
                " A obrigatoriedade é decidida no chamado.",
            ),
        ),
    ]
