# Generated by Django 5.2.9 on 2026-02-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0010_instalacaoitem_deve_configurar_instalacaoitem_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="coleta_confirmada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chamado",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("MAIS_ANTIGO", "Mais antigo (padrão)"),
                    ("BAIXA", "Baixa"),
                    ("MEDIA", "Média"),
                    ("ALTA", "Alta"),
                    ("CRITICA", "Crítica"),
                ],
                db_index=True,
                default="MAIS_ANTIGO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ticket_externo_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ticket_externo_sistema",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("EM_EXECUCAO", "Em execução"),
                    ("AGUARDANDO_NF", "Aguardando NF"),
                    ("AGUARDANDO_COLETA", "Aguardando coleta"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="ABERTO",
                max_length=20,
            ),
        ),
    ]
