# Generated by Django 5.2.9 on 2026-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0012_alter_chamado_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamado",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("MAIS_ANTIGO", "Padrão"),
                    ("BAIXA", "Baixa"),
                    ("MEDIA", "Média"),
                    ("ALTA", "Alta"),
                    ("CRITICA", "Crítica"),
                ],
                db_index=True,
                default="MAIS_ANTIGO",
                max_length=20,
            ),
        ),
    ]
