# Generated by Django 5.2.9 on 2026-02-07 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0013_alter_chamado_prioridade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chamado",
            name="servicenow_numero",
        ),
    ]
