# Generated by Django 5.2.9 on 2026-02-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0008_projeto_cor_slug"),
        ("execucao", "0014_remove_chamado_servicenow_numero"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chamado",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ticket_externo_sistema__isnull", False),
                    models.Q(("ticket_externo_sistema", ""), _negated=True),
                    ("ticket_externo_id__isnull", False),
                    models.Q(("ticket_externo_id", ""), _negated=True),
                ),
                fields=("ticket_externo_sistema", "ticket_externo_id"),
                name="uq_chamado_ticket_externo_sistema_id",
            ),
        ),
    ]
