# Generated by Django 5.2.9 on 2026-02-08 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone

import execucao.models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0015_chamado_uq_chamado_ticket_externo_sistema_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(default=execucao.models._default_expires_at)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("TIMEOUT", "Timeout"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_sessions",
                        to="execucao.chamado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["chamado", "ended_at"], name="execucao_ex_chamado_d01c5c_idx"
                    ),
                    models.Index(
                        fields=["usuario", "ended_at"], name="execucao_ex_usuario_988b76_idx"
                    ),
                    models.Index(fields=["expires_at"], name="execucao_ex_expires_292641_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("expires_at__gt", django.db.models.functions.datetime.Now()),
                        ),
                        fields=("chamado",),
                        name="uniq_active_execution_session_per_chamado",
                    )
                ],
            },
        ),
    ]
