# Generated by Django 5.2.9 on 2026-02-08 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0016_executionsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="executionsession",
            name="uniq_active_execution_session_per_chamado",
        ),
        migrations.AddConstraint(
            model_name="executionsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("chamado",),
                name="uniq_open_execution_session_per_chamado",
            ),
        ),
    ]
