# Generated by Django 5.2.9 on 2026-02-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0018_alter_executionsession_ended_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionsession",
            name="ended_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                    ("TIMEOUT", "Timeout"),
                    ("OUTRO", "Outro"),
                    ("ADMIN_TAKE", "Admin tomou a sessão"),
                    ("SAVE", "Salvar execução"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
