# Generated by Django 5.2.9 on 2026-02-10 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0019_alter_executionsession_ended_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacaoitem",
            name="configurado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instalacaoitem",
            name="configurado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execucao_itens_configurados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
