# Generated by Django 5.2.9 on 2026-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0020_instalacaoitem_configurado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ABERTURA", "Em abertura"),
                    ("ABERTO", "Aberto"),
                    ("EM_CONFIGURACAO", "Em configuração"),
                    ("EM_EXECUCAO", "Em execução"),
                    ("AGUARDANDO_NF", "Aguardando NF"),
                    ("AGUARDANDO_COLETA", "Aguardando coleta"),
                    ("FINALIZADO", "Finalizado"),
                ],
                db_index=True,
                default="EM_ABERTURA",
                max_length=20,
            ),
        ),
    ]
