# Generated by Django 5.2.9 on 2026-02-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0021_alter_chamado_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="coleta_confirmada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chamado",
            name="coleta_confirmada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados_coleta_confirmada",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
