# Generated by Django 5.2.14 on 2026-05-31 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtivoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(db_index=True, max_length=80)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_evento', models.CharField(choices=[('INSTALADO', 'Instalado'), ('RETORNADO', 'Retornado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('loja_codigo', models.CharField(db_index=True, max_length=50)),
                ('loja_nome', models.CharField(max_length=120)),
                ('chamado_id', models.IntegerField(db_index=True)),
                ('protocolo', models.CharField(max_length=32)),
                ('equipamento_nome', models.CharField(max_length=120)),
                ('tipo_equipamento', models.CharField(blank=True, default='', max_length=80)),
                ('ocorrido_em', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Timeline de Ativo',
                'verbose_name_plural': 'Timelines de Ativos',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['ativo', 'ocorrido_em'], name='historico_h_ativo_ea0336_idx'), models.Index(fields=['loja_codigo', 'ocorrido_em'], name='historico_h_loja_co_836956_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado_id', models.IntegerField(db_index=True, unique=True)),
                ('protocolo', models.CharField(db_index=True, max_length=32)),
                ('tipo', models.CharField(max_length=20)),
                ('status_final', models.CharField(max_length=20)),
                ('loja_codigo', models.CharField(db_index=True, max_length=50)),
                ('loja_nome', models.CharField(max_length=120)),
                ('projeto_codigo', models.CharField(max_length=50)),
                ('projeto_nome', models.CharField(max_length=120)),
                ('subprojeto_codigo', models.CharField(max_length=50)),
                ('subprojeto_nome', models.CharField(max_length=120)),
                ('kit_nome', models.CharField(max_length=120)),
                ('contabilidade_numero', models.CharField(blank=True, default='', max_length=40)),
                ('nf_saida_numero', models.CharField(blank=True, default='', max_length=40)),
                ('criado_em', models.DateTimeField()),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('itens_snapshot', models.JSONField(default=list)),
                ('evidencias_snapshot', models.JSONField(default=list)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_finalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Execução',
                'verbose_name_plural': 'Históricos de Execução',
                'ordering': ['-finalizado_em', '-criado_em'],
            },
        ),
    ]
